// 样式对象

const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    gap: '16px',
    padding: '16px',
    boxSizing: 'border-box',
  },
  main: {
    display: 'flex',
    flex: '1',
    gap: '16px',
    minHeight: 0,
  },
  voiceGridWrapper: {
    maxHeight: '240px',
    overflowY: 'auto',
    marginTop: '8px',
    paddingRight: '4px',
  },
  voiceGrid: {
    display: 'grid',
    gap: '8px',
  },
  voiceItem: {
    padding: '8px 6px',
    borderRadius: '8px',
    border: '2px solid transparent',
    cursor: 'pointer',
    textAlign: 'center',
    fontSize: '12px',
    transition: 'all 0.2s',
    position: 'relative',
  },
  actionBtn: {
    position: 'absolute',
    top: '2px',
    fontSize: '13px',
    lineHeight: 1,
    cursor: 'pointer',
    fontWeight: '700',
    width: '18px',
    height: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    transition: 'opacity 0.2s',
    background: 'var(--background, #1e293b)',
    zIndex: 1,
  },
  addVoiceItem: {
    padding: '8px 6px',
    borderRadius: '8px',
    border: '2px dashed var(--border, #444)',
    cursor: 'pointer',
    textAlign: 'center',
    fontSize: '12px',
    color: 'var(--muted-foreground, #999)',
    transition: 'all 0.2s',
  },
  addForm: {
    marginTop: '8px',
    padding: '10px',
    borderRadius: '8px',
    border: '1px solid var(--border, #444)',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  controlsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
  },
  audioPlayer: {
    width: '100%',
    height: '40px',
    borderRadius: '8px',
    outline: 'none',
  },
  audioPlayerInline: {
    flex: '1',
    minWidth: '200px',
    height: '40px',
    borderRadius: '8px',
    outline: 'none',
  },
  sliderRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginTop: '4px',
    width: '100%',
  },
  sliderValue: {
    fontSize: '13px',
    fontWeight: '600',
    minWidth: '36px',
    textAlign: 'right',
  },
  charCount: {
    fontSize: '11px',
    textAlign: 'right',
    marginTop: '4px',
    opacity: 0.6,
  },
  tabBar: {
    display: 'flex',
    gap: '4px',
    padding: '4px',
    borderRadius: '8px',
    background: 'var(--muted, #2a4a6c)',
  },
  tabBtn: {
    flex: '1',
    padding: '8px 12px',
    borderRadius: '6px',
    border: 'none',
    background: 'transparent',
    color: 'var(--muted-foreground, #cbd5e1)',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.2s',
  },
  tabBtnActive: {
    background: 'var(--primary, #4fc3f7)',
    color: '#0b1220',
  },
  roleList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '8px',
  },
  roleItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 8px',
    borderRadius: '999px',
    fontSize: '12px',
    background: 'var(--muted, #2a4a6c)',
    border: '1px solid var(--border, #444)',
  },
  roleRemove: {
    cursor: 'pointer',
    fontWeight: '700',
    opacity: 0.7,
    lineHeight: 1,
  },
  msgList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '8px',
  },
  msgItem: {
    padding: '10px',
    borderRadius: '8px',
    border: '1px solid var(--border, #444)',
    background: 'var(--card, #1e293b)',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  msgTopRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  msgIndex: {
    fontSize: '12px',
    fontWeight: '700',
    opacity: '0.7',
    minWidth: '24px',
  },
  msgActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginLeft: 'auto',
  },
  iconBtn: {
    width: '26px',
    height: '26px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '6px',
    border: '1px solid var(--border, #444)',
    background: 'transparent',
    color: 'var(--muted-foreground, #cbd5e1)',
    cursor: 'pointer',
    fontSize: '13px',
    padding: 0,
  },
  toolbarRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
    marginTop: '12px',
  },
  emptyHint: {
    fontSize: '13px',
    opacity: 0.6,
    textAlign: 'center',
    padding: '16px 0',
  },
};

export default styles;
